apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuers-app
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/hsudbrock/argocd-apps.git'
    targetRevision: main
    path: cert-manager-issuers
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
