apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator-app
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.external-secrets.io'
    targetRevision: 0.9.0
    chart: external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
