apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server-app
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://kubernetes-sigs.github.io/metrics-server/'
    targetRevision: 3.10.0
    chart: metrics-server
    helm:
      values: |
        args:
          - "--kubelet-insecure-tls"
  destination:
    server: https://kubernetes.default.svc
    namespace: metrics-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
