apiVersion: v1
kind: Secret
metadata:
  name: authelia-users
  namespace: authelia
type: Opaque
stringData:
  users_database.yml: |
    users:
      admin:
        displayname: "Admin User"
        password: "$argon2id$v=19$m=65536,t=3,p=4$iiLiGUvGU2GNeXhd06L5VQ$7KAwwBHU0Np+GrFYWqE7qtfehAcoi61s7Fxgod78b1o"
        email: "admin@hsudbrock.de"
        groups:
          - admins
