apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack-app
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 80.7.0
    chart: kube-prometheus-stack
    helm:
      values: |
        grafana:
          service:
            annotations:
              tailscale.com/expose: "true"
              tailscale.com/hostname: grafana
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-prometheus-stack
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        # Use priviledged namespace to permit node exporter daemonset to schedule in other namespaces
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/warn: privileged
        pod-security.kubernetes.io/audit: privileged
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # Need explicit ServerSideApply because some manifests are big
      - ServerSideApply=true
