apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail-app
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 6.17.1
    chart: promtail
    helm:
      values: |
        config:
          clients:
            - url: http://loki-app.loki.svc:3100/loki/api/v1/push
  destination:
    server: https://kubernetes.default.svc
    namespace: promtail
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/warn: privileged
        pod-security.kubernetes.io/audit: privileged
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
